# Generated by Django 5.2.11 on 2026-03-21 22:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Relevamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kit', models.PositiveSmallIntegerField(choices=[(1, 'Huerta familiar inicial'), (2, 'Huerta familiar ampliada'), (3, 'Huerta comunitaria'), (4, 'Huerta familiar productiva'), (5, 'Huerta productiva escalable')], verbose_name='Kit')),
                ('observaciones', models.CharField(blank=True, default=None, max_length=5000, null=True, verbose_name='Oberservaciones')),
                ('latitud', models.DecimalField(decimal_places=16, max_digits=19, verbose_name='Latitud')),
                ('longitud', models.DecimalField(decimal_places=16, max_digits=19, verbose_name='Longitud')),
                ('puntaje', models.PositiveSmallIntegerField(default=0, verbose_name='Puntaje')),
                ('foto1', models.ImageField(blank=True, default=None, null=True, upload_to='jakaru_pora/relevamiento', verbose_name='Foto 1')),
                ('foto2', models.ImageField(blank=True, default=None, null=True, upload_to='jakaru_pora/relevamiento', verbose_name='Foto 2')),
                ('beneficiario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.beneficiario')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('id',),
            },
        ),
    ]
